version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 5555:80
    volumes:
        - pgadmin:/var/lib/pgadmin
    depends_on:
        - postgres

  api:
    build:
        context: .
        dockerfile: Dockerfile
    image: jwt-api-image:latest
    container_name: jwt-api-app
    hostname: jwt-hostname
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
    postgres:
    pgadmin: